### ISSUE TITLE
Clearer answer format instructions

### ISSUE THREAD

**Issue by henrikmdev** [LauritsCSB/QuizMaker#4]
https://github.com/LauritsCSB/QuizMaker/blob/9f7f57f20d28cc35ccdca67ca9c37217f5d64242/Program.cs#L51

I assume the user should enter his or her answer via a number. But what if the user types out a whole answer? Maybe tell the user to pick one of the answers and specify the number that is associated with that answer.

**Comment by LauritsCSB** [comment]
That's true! I was so blind to this.

**Comment by incredibleLeitman** [comment]
You may also want to let your "TakeAnswer" method already return the "internal" index of the answer.

Otherwise you always need to substract 1 after calling this function.


A good rule of thumb is, whenever the user enters a value, you directly convert it to internal state (reducing indizes by one to start from zero) 
and do the opposite when displaying information to the user

**Comment by LauritsCSB** [comment]
I actually thought of this aswell! Must remember to write ideas and todo's down.
